on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n castnestnodesteamer -g castnestnodesteamerb928-rg --location "UK West" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n castnestnodesteamer --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n castnestnodesteamer --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n castnestnodesteamer --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: castnestnodesteamer.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t castnestnodesteamer.azurecr.io/streamer:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push castnestnodesteamer.azurecr.io/streamer:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_streamer_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep castneststearmers | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace castneststearmers`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: castneststearmers
        container-registry-url: castnestnodesteamer.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: streamerdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: castneststearmers
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          castnestnodesteamer.azurecr.io/streamer:${{ github.sha }}
        imagepullsecrets: |
          streamerdockerauth   
